// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdGNFTDWidUFUVGWVZmAg8B5AsJ3JhssY',
    appId: '1:77490246666:web:eeea0153f5dae11593bbf3',
    messagingSenderId: '77490246666',
    projectId: 'robert-flutter-course-db',
    authDomain: 'robert-flutter-course-db.firebaseapp.com',
    storageBucket: 'robert-flutter-course-db.firebasestorage.app',
    measurementId: 'G-8QXJZ7C0R3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2hfxbdDcpR_Atjr4Rh5mKwz_DfmjCoUU',
    appId: '1:77490246666:android:a27d60756f3081f893bbf3',
    messagingSenderId: '77490246666',
    projectId: 'robert-flutter-course-db',
    storageBucket: 'robert-flutter-course-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNPGDs8mHRwOzyoBJNcxI6qvFm97OUWAA',
    appId: '1:77490246666:ios:1a886e62c570ca1093bbf3',
    messagingSenderId: '77490246666',
    projectId: 'robert-flutter-course-db',
    storageBucket: 'robert-flutter-course-db.firebasestorage.app',
    iosBundleId: 'com.example.flutterCourseEcommerceProject',
  );
}
